# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 02:31
from __future__ import unicode_literals

import civic_exam.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='civic_exam.Question')),
                ('value', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.Cat'),
        ),
        migrations.AddField(
            model_name='question',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.Subcat'),
        ),
    ]
