# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_exam', '0002_practice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwser',
            new_name='Answer',
        ),
    ]
