# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 04:19
from __future__ import unicode_literals

import civic_exam.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civic_exam', '0003_auto_20170606_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('select', models.IntegerField(null=True)),
                ('choices', models.CharField(default='', max_length=50)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.Answer')),
            ],
            bases=(models.Model, civic_exam.mixins.CommonMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('cat', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('num_q', models.IntegerField(blank=True, null=True)),
                ('exam_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='practice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.User'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic_exam.User'),
        ),
    ]
